Removing the <excludeDefault> element for now as it's causing the build to fail with:
[INFO] Reason: Failed to parse model from file 'C:\dev\maven\components\trunk\examples\maven-clover-plugin-samples\maven-clover-plugin-sample-simple\pom.xml'.
Error: 'Unrecognised tag: 'excludeDefaults' (position: START_TAG seen ...<reporting>\r\n    <excludeDefaults>... @22:22) '


git-svn-id: http://svn.apache.org/repos/asf/maven/components/trunk@291102 13f79535-47bb-0310-9956-ffa450edef68